driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default-recipe
    run_list:
    - recipe[adinauer-test-cookbook::default]
    includes: [
      'ubuntu-12.04',
    ]
