driver_plugin: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]

suites:
  - name: default-recipe-test-suite
    run_list:
    - recipe[adinauer-test-cookbook::default]
